### PR TITLE
Added some ideas of inefficiencies

### PR DESCRIPTION
**Pull request by AJEvans**
Could be used to set up some code for them to make more efficient.

### CODE REVIEW

**Comment by callaghanmt** [comment]
I like these. Good ideas.

**Comment by AJEvans** [comment]
No worries. Somewhere I have some code that displays all these (on purpose!), but it's in Java. If you work this up for real, let me know and I'll convert it into Python -- good practice for me! :)

**Comment by MattForshaw** [comment]
@AJEvans I'd be really interested to see the Java version displaying these inefficiencies, sounds cool!

**Comment by AJEvans** [comment]
Gave me an excuse to wrap it in a webpage for my beginner Java students @MattForshaw ; not quite all of them after all, but some, and some others: 
http://www.geog.leeds.ac.uk/courses/other/programming/materials/practice/index.html
-> Efficiency
(rest of the course here, if you're interested: http://www.geog.leeds.ac.uk/courses/other/programming/core/ )

**Pull request merged**
